@startuml FlashcardUseCase

left to right direction
skinparam packageStyle rect

actor User
actor UserAdmin
actor Server

rectangle FlashcardWebApp {
    folder NormalUser {
        User -- (Login)
        (Login) -- Server
        User -- (Fetch Question Set)
        (Fetch Question Set) -- Server
        (Fetch Question Set) <. (Answer Questions) : <<extends>>
        (Skip Questions) .> (Fetch Question Set) : <<extends>>
        (Answer Questions) .> (Update Scores) : <<includes>>
        (Update Scores) -- Server

        User --- (View Score Leaderboard)
        (View Score Leaderboard) -- Server
    }

    folder AdminUser {
        UserAdmin -- (Login)

        UserAdmin -- (Add User)
        (Add User) -- Server

        UserAdmin -- (View User Info)
        (View User Info) -- Server

        UserAdmin -- (Update User Info)
        (Update User Info) -- Server

        UserAdmin -- (Remove User)
        (Remove User) -- Server
    }
}

@enduml